### PR TITLE
Ship drawer

### PR DESCRIPTION
**Pull request by jushe**
There is a problem with shipDrawer when you close it,but it would be resolved after I set the "ship name" data

### CODE REVIEW

**Comment by Wafer-Li** [comment]
@jushe 
Keep working on it.
When you finish, notify me, and **I will merge it**

**Comment by Crepusculo** [comment]
you add oil

**Comment by xdqi** [comment]
add oil

2015-09-07 11:59 GMT+08:00 Graham Tang <notifications@github.com>:

> you add oil
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KantaiWiki/KCW_Mobile/pull/10#issuecomment-138176975>.
>



-- 

*Sincerely,K*

**Comment by jushe** [comment]
Well, I think I have finish it now.

**Pull request merged**
